# Generated by Django 3.2.6 on 2023-10-21 16:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Azienda')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCorso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255, verbose_name='Titolo Video')),
                ('video_file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='File Video')),
                ('aziende', models.ManyToManyField(related_name='video_corsi', to='home.Azienda', verbose_name='Aziende')),
            ],
            options={
                'verbose_name': 'Video Corso',
                'verbose_name_plural': 'Video Corsi',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=255, verbose_name='Cognome')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utenti', to='home.azienda', verbose_name='Azienda')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatoVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizzato', models.BooleanField(default=False, verbose_name='Visualizzato')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stati_video', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
                ('video_corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stati_video', to='home.videocorso', verbose_name='Video Corso')),
            ],
            options={
                'verbose_name': 'Stato Video',
                'verbose_name_plural': 'Stati Video',
                'unique_together': {('utente', 'video_corso')},
            },
        ),
    ]
