# Generated by Django 4.2.7 on 2024-01-03 18:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Azienda",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome Azienda")),
            ],
            options={
                "verbose_name": "Azienda",
                "verbose_name_plural": "Aziende",
            },
        ),
        migrations.CreateModel(
            name="Corso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "titolo",
                    models.CharField(max_length=255, verbose_name="Titolo Corso"),
                ),
                ("descrizione", models.TextField(blank=True, null=True)),
                (
                    "data_inizio",
                    models.DateField(blank=True, null=True, verbose_name="Data inizio"),
                ),
                (
                    "data_fine",
                    models.DateField(blank=True, null=True, verbose_name="Data fine"),
                ),
                (
                    "durata",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durata in giorni"
                    ),
                ),
                (
                    "data_creazione",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "aziende",
                    models.ManyToManyField(
                        related_name="corsi", to="home.azienda", verbose_name="Aziende"
                    ),
                ),
            ],
            options={
                "verbose_name": "Corso",
                "verbose_name_plural": "Corsi",
            },
        ),
        migrations.CreateModel(
            name="Domanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testo", models.TextField()),
            ],
            options={
                "verbose_name": "Domanda",
                "verbose_name_plural": "Domande",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=255)),
                (
                    "corso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="home.corso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
            },
        ),
        migrations.CreateModel(
            name="VideoCorso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "titolo",
                    models.CharField(max_length=255, verbose_name="Titolo Video"),
                ),
                ("descrizione", models.TextField(blank=True, null=True)),
                ("ordine", models.PositiveIntegerField(default=0)),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        upload_to="videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "webm", "ogg"]
                            )
                        ],
                        verbose_name="File Video",
                    ),
                ),
                (
                    "poster_file",
                    models.ImageField(
                        blank=True, upload_to="posters/", verbose_name="Miniature foto"
                    ),
                ),
                (
                    "external_url",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Url CDN"
                    ),
                ),
                (
                    "durata_video",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Durata del video in secondi",
                    ),
                ),
                (
                    "aziende",
                    models.ManyToManyField(
                        related_name="video_corsi",
                        to="home.azienda",
                        verbose_name="Aziende",
                    ),
                ),
                (
                    "corso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_corsi",
                        to="home.corso",
                        verbose_name="Corso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Corso",
                "verbose_name_plural": "Video Corsi",
                "ordering": ["ordine"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("risultati", models.JSONField(default=dict)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.quiz"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentativo Quiz",
                "verbose_name_plural": "Tentativi Quiz",
            },
        ),
        migrations.CreateModel(
            name="OpzioneRisposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testo_opzione", models.TextField()),
                ("corretta", models.BooleanField(default=False)),
                (
                    "domanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opzioni",
                        to="home.domanda",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpzioneRisposta",
                "verbose_name_plural": "Opzioni Risposta",
            },
        ),
        migrations.AddField(
            model_name="domanda",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domande",
                to="home.quiz",
            ),
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "azienda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utenti",
                        to="home.azienda",
                        verbose_name="Azienda",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_corsi_spec",
                    models.ManyToManyField(
                        related_name="utenti",
                        to="home.videocorso",
                        verbose_name="Video Corsi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profilo",
                "verbose_name_plural": "Profili",
            },
        ),
        migrations.AddField(
            model_name="corso",
            name="docenti",
            field=models.ManyToManyField(
                related_name="corsi_insegnati",
                to="home.customuser",
                verbose_name="Docenti",
            ),
        ),
        migrations.AddField(
            model_name="azienda",
            name="staff_users",
            field=models.ManyToManyField(
                blank=True, related_name="aziende", to="home.customuser"
            ),
        ),
        migrations.CreateModel(
            name="AttestatiVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "data_conseguimento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data conseguimento"
                    ),
                ),
                (
                    "data_download",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data download"
                    ),
                ),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="attestati/"),
                ),
                (
                    "corso",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.corso",
                        verbose_name="Corso",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attestato Video",
                "verbose_name_plural": "Attestati Video",
            },
        ),
        migrations.CreateModel(
            name="StatoVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "iniziato",
                    models.BooleanField(default=False, verbose_name="Video iniziato"),
                ),
                (
                    "completato",
                    models.BooleanField(default=False, verbose_name="Video completato"),
                ),
                (
                    "data_prima_visual",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data prima apertura del video",
                    ),
                ),
                (
                    "data_ultima_visual",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data ultima apertura del video",
                    ),
                ),
                (
                    "data_completamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data completamento video"
                    ),
                ),
                (
                    "totale_secondi_visualizzati",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Totale secondi visualizzati",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stati_video",
                        to="home.customuser",
                        verbose_name="Utente",
                    ),
                ),
                (
                    "video_corso",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stati_video",
                        to="home.videocorso",
                        verbose_name="Video Corso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stato Video",
                "verbose_name_plural": "Stati Video",
                "unique_together": {("utente", "video_corso")},
            },
        ),
    ]
