# Generated by Django 3.2.6 on 2023-10-22 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_videocorso_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utenti', to='home.azienda', verbose_name='Azienda'),
        ),
    ]
