# Generated by Django 3.2.6 on 2023-10-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='Changeme12!', max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='Username'),
        ),
    ]
