# Generated by Django 3.2.6 on 2023-10-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
