# Generated by Django 4.2.6 on 2023-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocorso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
