# Generated by Django 4.2.6 on 2023-10-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_alter_videocorso_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='statovideo',
            name='completato',
            field=models.BooleanField(default=False, verbose_name='Completato'),
        ),
        migrations.AddField(
            model_name='statovideo',
            name='data_prima_visual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data prima apertura del video'),
        ),
        migrations.AddField(
            model_name='statovideo',
            name='data_ultima_visual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data ultima apertura del video'),
        ),
        migrations.AddField(
            model_name='statovideo',
            name='totale_minuti_visualizzati',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocorso',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocorso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AttestatiVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conseguimento', models.DateTimeField(blank=True, null=True, verbose_name='Data conseguimento')),
                ('data_download', models.DateTimeField(blank=True, null=True, verbose_name='Data download')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='attestati/')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
                ('video_corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.videocorso', verbose_name='Video Corso')),
            ],
        ),
    ]
