# Generated by Django 4.2.6 on 2023-10-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_customuser_cognome_remove_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azienda',
            options={'verbose_name': 'Azienda', 'verbose_name_plural': 'Aziende'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Profilo', 'verbose_name_plural': 'Profili'},
        ),
        migrations.AddField(
            model_name='azienda',
            name='staff_users',
            field=models.ManyToManyField(related_name='staff_users', to='home.customuser'),
        ),
    ]
