# Generated by Django 4.2.6 on 2023-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_azienda_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='staff_users',
            field=models.ManyToManyField(blank=True, related_name='staff_users', to='home.customuser'),
        ),
    ]
