# Generated by Django 4.2.6 on 2023-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_azienda_staff_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='staff_users',
            field=models.ManyToManyField(blank=True, related_name='aziende', to='home.customuser'),
        ),
    ]
