# Generated by Django 4.2.6 on 2023-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocorso',
            name='external_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Url CDN'),
        ),
    ]
