# Generated by Django 4.2.6 on 2023-10-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_statovideo_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statovideo',
            name='video_corso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stati_video', to='home.videocorso', verbose_name='Video Corso'),
        ),
    ]
