# Generated by Django 4.2.6 on 2023-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_statovideo_video_corso'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocorso',
            name='poster_file',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Miniature foto'),
        ),
    ]
