# Generated by Django 4.2.6 on 2023-10-28 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_videocorso_poster_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocorso',
            name='poster_file',
            field=models.ImageField(blank=True, upload_to='media/posters/', verbose_name='Miniature foto'),
        ),
        migrations.AlterField(
            model_name='videocorso',
            name='video_file',
            field=models.FileField(blank=True, upload_to='media/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='File Video'),
        ),
    ]
