# Generated by Django 4.2.6 on 2023-10-28 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_videocorso_poster_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocorso',
            name='poster_file',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Miniature foto'),
        ),
        migrations.AlterField(
            model_name='videocorso',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='File Video'),
        ),
    ]
