# Generated by Django 4.2.6 on 2023-10-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_videocorso_poster_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statovideo',
            name='visualizzato',
        ),
        migrations.AddField(
            model_name='statovideo',
            name='iniziato',
            field=models.BooleanField(default=False, verbose_name='Video iniziato'),
        ),
        migrations.AlterField(
            model_name='statovideo',
            name='completato',
            field=models.BooleanField(default=False, verbose_name='Video completato'),
        ),
    ]
