# Generated by Django 4.2.6 on 2023-10-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_statovideo_visualizzato_statovideo_iniziato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statovideo',
            name='data_completamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data completamento video'),
        ),
    ]
