# Generated by Django 4.2.6 on 2023-10-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_statovideo_totale_minuti_visualizzati_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statovideo',
            name='durata_video',
        ),
        migrations.AddField(
            model_name='videocorso',
            name='durata_video',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durata del video in secondi'),
        ),
    ]
