# Generated by Django 4.2.6 on 2023-10-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_statovideo_durata_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statovideo',
            name='totale_secondi_visualizzati',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale secondi visualizzati'),
        ),
    ]
