# Generated by Django 4.2.6 on 2023-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_alter_statovideo_totale_secondi_visualizzati"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="video_corsi_spec",
            field=models.ManyToManyField(
                related_name="utenti", to="home.videocorso", verbose_name="Video Corsi"
            ),
        ),
    ]
