# Generated by Django 4.2.6 on 2023-11-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_alter_customuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testo", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=255)),
                (
                    "video_corso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="home.videocorso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpzioneRisposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testo_opzione", models.TextField()),
                ("corretta", models.BooleanField(default=False)),
                (
                    "domanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opzioni",
                        to="home.domanda",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="domanda",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domande",
                to="home.quiz",
            ),
        ),
    ]
