# Generated by Django 4.2.6 on 2023-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_alter_attestativideo_options_alter_domanda_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizattempt",
            options={
                "verbose_name": "Tentativo Quiz",
                "verbose_name_plural": "Tentativi Quiz",
            },
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="risultati",
            field=models.JSONField(default=dict),
        ),
    ]
