# Generated by Django 4.2.7 on 2023-12-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_alter_quizattempt_options_quizattempt_risultati"),
    ]

    operations = [
        migrations.CreateModel(
            name="Corso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "titolo",
                    models.CharField(max_length=255, verbose_name="Titolo Corso"),
                ),
                ("descrizione", models.TextField(blank=True, null=True)),
                (
                    "data_inizio",
                    models.DateField(blank=True, null=True, verbose_name="Data inizio"),
                ),
                (
                    "data_fine",
                    models.DateField(blank=True, null=True, verbose_name="Data fine"),
                ),
                (
                    "durata",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Durata in giorni"
                    ),
                ),
                (
                    "data_creazione",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data creazione"
                    ),
                ),
                (
                    "aziende",
                    models.ManyToManyField(
                        related_name="corsi", to="home.azienda", verbose_name="Aziende"
                    ),
                ),
                (
                    "docenti",
                    models.ManyToManyField(
                        related_name="corsi_insegnati",
                        to="home.customuser",
                        verbose_name="Docenti",
                    ),
                ),
                (
                    "video_corsi",
                    models.ManyToManyField(
                        related_name="corsi",
                        to="home.videocorso",
                        verbose_name="Video Corsi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corso",
                "verbose_name_plural": "Corsi",
            },
        ),
    ]
