# Generated by Django 4.2.7 on 2023-12-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_corso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="video_corso",
        ),
        migrations.AddField(
            model_name="quiz",
            name="corso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="home.corso",
            ),
        ),
    ]
