# Generated by Django 4.2.7 on 2023-12-29 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_remove_quiz_video_corso_quiz_corso"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attestativideo",
            name="video_corso",
        ),
        migrations.AddField(
            model_name="attestativideo",
            name="corso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.corso",
                verbose_name="Corso",
            ),
        ),
    ]
