# Generated by Django 4.2.7 on 2023-12-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_remove_attestativideo_video_corso_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videocorso",
            options={
                "ordering": ["ordine"],
                "verbose_name": "Video Corso",
                "verbose_name_plural": "Video Corsi",
            },
        ),
        migrations.AddField(
            model_name="videocorso",
            name="ordine",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
