# Generated by Django 4.2.7 on 2023-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_remove_corso_video_corsi_corso_video_corsi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="corso",
            name="video_corsi",
        ),
        migrations.AddField(
            model_name="corso",
            name="video_corsi",
            field=models.ManyToManyField(
                related_name="corsi", to="home.videocorso", verbose_name="Video Corsi"
            ),
        ),
    ]
